// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_response`, `fetch_and_cache_zip`, `get_cache`, `get_gateways`, `handle_request`

Future<void> setGateways({required List<String> gateways}) =>
    RustLib.instance.api.crateApiServerSetGateways(gateways: gateways);

Future<void> startLocalServer() =>
    RustLib.instance.api.crateApiServerStartLocalServer();
