// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_wallet_lock`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WalletInfo`

Future<String> generateWallet() =>
    RustLib.instance.api.crateApiWalletGenerateWallet();

Future<String> importWallet({required String privateKeyHex}) => RustLib
    .instance
    .api
    .crateApiWalletImportWallet(privateKeyHex: privateKeyHex);

Future<String> encryptAndSaveWallet({
  required String password,
  required String dirPath,
}) => RustLib.instance.api.crateApiWalletEncryptAndSaveWallet(
  password: password,
  dirPath: dirPath,
);

Future<String> loadAndDecryptWallet({
  required String password,
  required String filePath,
}) => RustLib.instance.api.crateApiWalletLoadAndDecryptWallet(
  password: password,
  filePath: filePath,
);

Future<String> signMessage({required String message}) =>
    RustLib.instance.api.crateApiWalletSignMessage(message: message);

Future<String> getDid() => RustLib.instance.api.crateApiWalletGetDid();

Future<String> getAddress() => RustLib.instance.api.crateApiWalletGetAddress();
